# Generated by Django 5.1.14 on 2025-11-24 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpage',
            name='group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifier shared by all language variants of the same logical destination.'),
        ),
    ]
