# Generated by Django 5.1.14 on 2025-11-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_seed_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='country_hero_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for this page (recommended: 1200x600px)', null=True, upload_to='page_hero_images/'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'), ('pt', 'Português')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=150)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='city_hero_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cms.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['order', 'name'],
                'unique_together': {('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150)),
                ('is_published', models.BooleanField(default=False)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='destination_hero_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='cms.city')),
            ],
            options={
                'ordering': ['slug'],
                'unique_together': {('city', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DestinationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'), ('pt', 'Português')], max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.destination')),
            ],
            options={
                'ordering': ['destination__slug', 'locale'],
                'unique_together': {('destination', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='DestinationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('image', 'Image Block'), ('text_image', 'Text + Image Block'), ('cta', 'Call to Action')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, help_text='Section title (optional)', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Section content text')),
                ('image', models.ImageField(blank=True, help_text='Section image (optional)', null=True, upload_to='destination_section_images/')),
                ('cta_label', models.CharField(blank=True, help_text='Call-to-action button text', max_length=255)),
                ('cta_url', models.CharField(blank=True, help_text='Call-to-action URL or path', max_length=500)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.destinationtranslation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('image', 'Image Block'), ('text_image', 'Text + Image Block'), ('cta', 'Call to Action')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, help_text='Section title (optional)', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Section content text')),
                ('image', models.ImageField(blank=True, help_text='Section image (optional)', null=True, upload_to='page_section_images/')),
                ('cta_label', models.CharField(blank=True, help_text='Call-to-action button text', max_length=255)),
                ('cta_url', models.CharField(blank=True, help_text='Call-to-action URL or path', max_length=500)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.pagetranslation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
