# Generated by Django 5.1.14 on 2025-11-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_country_pagetranslation_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog_hero_images/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.blogcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'), ('pt', 'Português')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Override post hero image for this locale', null=True, upload_to='blog_translation_images/')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.blogpost')),
            ],
            options={
                'ordering': ['locale'],
                'unique_together': {('post', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='BlogPostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Block'), ('image', 'Image Block'), ('text_image', 'Text + Image Block'), ('cta', 'Call to Action')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, help_text='Section title (optional)', max_length=255)),
                ('body', models.TextField(blank=True, help_text='Section content text')),
                ('image', models.ImageField(blank=True, help_text='Section image (optional)', null=True, upload_to='blog_section_images/')),
                ('cta_label', models.CharField(blank=True, help_text='Call-to-action button text', max_length=255)),
                ('cta_url', models.CharField(blank=True, help_text='Call-to-action URL or path', max_length=500)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='cms.blogposttranslation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
