# Generated by Django 5.1.14 on 2025-11-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_blogcategory_blogpost_blogposttranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(blank=True, help_text='Display name for this media file', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero slide image (recommended: 1920x800px)', upload_to='blog_hero_slides/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption text overlay', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='cms.blogposttranslation')),
            ],
            options={
                'verbose_name': 'Blog Post Hero Slide',
                'verbose_name_plural': 'Blog Post Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DestinationHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero slide image (recommended: 1920x800px)', upload_to='destination_hero_slides/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption text overlay', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='cms.destinationtranslation')),
            ],
            options={
                'verbose_name': 'Destination Hero Slide',
                'verbose_name_plural': 'Destination Hero Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero slide image (recommended: 1920x800px)', upload_to='page_hero_slides/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption text overlay', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='cms.pagetranslation')),
            ],
            options={
                'verbose_name': 'Page Hero Slide',
                'verbose_name_plural': 'Page Hero Slides',
                'ordering': ['order'],
            },
        ),
    ]
