# Generated by Django 5.1.14 on 2025-11-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_mediafile_blogpostheroslide_destinationheroslide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'), ('pt', 'Português')], max_length=5)),
                ('title', models.CharField(help_text='Footer section title', max_length=100)),
                ('body', models.TextField(blank=True, help_text='Footer section content (optional)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the footer (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Footer Block',
                'verbose_name_plural': 'Footer Blocks',
                'ordering': ['locale', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description for listing pages'),
        ),
        migrations.AddField(
            model_name='country',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description for listing pages'),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured destinations'),
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for filtering (e.g., historical, museum, beach)', max_length=500),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Link text', max_length=100)),
                ('url', models.CharField(help_text='URL (can be relative or absolute)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the footer block')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cms.footerblock')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'), ('pt', 'Português')], max_length=5)),
                ('label', models.CharField(help_text='Display text for the menu item', max_length=100)),
                ('url', models.CharField(blank=True, help_text='External URL (e.g., https://example.com)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the navigation menu (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this item in the navigation')),
                ('blog_category', models.ForeignKey(blank=True, help_text='Link to a blog category', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.blogcategory')),
                ('destination', models.ForeignKey(blank=True, help_text='Link to a destination', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.destination')),
                ('page', models.ForeignKey(blank=True, help_text='Link to a CMS page', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['locale', 'order', 'label'],
            },
        ),
    ]
