# Generated by Django 5.1.14 on 2025-11-25 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_footerblock_city_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Unique identifier for this category (e.g., 'city-breaks', 'beaches')", max_length=150, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on homepage (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Category',
                'verbose_name_plural': 'Homepage Categories',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='HomepageCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('nl', 'Nederlands'), ('es', 'Español'), ('pt', 'Português')], max_length=5)),
                ('title', models.CharField(help_text='Display title for this category', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description for the category card')),
                ('image', models.ImageField(help_text='Category card image (recommended: 800x600px)', upload_to='homepage_categories/')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this translation is published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.homepagecategory')),
            ],
            options={
                'verbose_name': 'Homepage Category Translation',
                'verbose_name_plural': 'Homepage Category Translations',
                'ordering': ['category__order', 'locale'],
                'unique_together': {('category', 'locale')},
            },
        ),
    ]
