# Generated by Django 5.1.14 on 2025-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_homepage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecategorytranslation',
            name='image',
            field=models.ImageField(blank=True, help_text='Category card image (recommended: 800x600px)', null=True, upload_to='homepage_categories/'),
        ),
    ]
