# Generated by Django 5.2.8 on 2025-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_homepagecategorytranslation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='jsonld_override',
            field=models.TextField(blank=True, help_text='Custom JSON-LD data (optional JSON override)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='jsonld_type',
            field=models.CharField(blank=True, help_text="JSON-LD schema type (e.g., 'Article', 'BlogPosting')", max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional, falls back to meta_description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional, falls back to meta_title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_enabled',
            field=models.BooleanField(default=True, help_text='Enable SEO optimizations for this blog post'),
        ),
        migrations.AddField(
            model_name='city',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='jsonld_override',
            field=models.TextField(blank=True, help_text='Custom JSON-LD data (optional JSON override)'),
        ),
        migrations.AddField(
            model_name='city',
            name='jsonld_type',
            field=models.CharField(blank=True, help_text="JSON-LD schema type (e.g., 'City', 'Place')", max_length=100),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional, falls back to meta_description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional, falls back to meta_title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_enabled',
            field=models.BooleanField(default=True, help_text='Enable SEO optimizations for this city'),
        ),
        migrations.AddField(
            model_name='country',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='jsonld_override',
            field=models.TextField(blank=True, help_text='Custom JSON-LD data (optional JSON override)'),
        ),
        migrations.AddField(
            model_name='country',
            name='jsonld_type',
            field=models.CharField(blank=True, help_text="JSON-LD schema type (e.g., 'Country', 'Place')", max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional, falls back to meta_description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional, falls back to meta_title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='seo_enabled',
            field=models.BooleanField(default=True, help_text='Enable SEO optimizations for this country'),
        ),
        migrations.AddField(
            model_name='destination',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='jsonld_override',
            field=models.TextField(blank=True, help_text='Custom JSON-LD data (optional JSON override)'),
        ),
        migrations.AddField(
            model_name='destination',
            name='jsonld_type',
            field=models.CharField(blank=True, help_text="JSON-LD schema type (e.g., 'TouristAttraction', 'Place')", max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional, falls back to meta_description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional, falls back to meta_title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='seo_enabled',
            field=models.BooleanField(default=True, help_text='Enable SEO optimizations for this destination'),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='jsonld_override',
            field=models.TextField(blank=True, help_text='Custom JSON-LD data (optional JSON override)'),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='jsonld_type',
            field=models.CharField(blank=True, help_text="JSON-LD schema type (e.g., 'CategoryCode', 'Thing')", max_length=100),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (recommended: 150-160 chars)', max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title (recommended: 50-60 chars)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional, falls back to meta_description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional, falls back to meta_title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepagecategory',
            name='seo_enabled',
            field=models.BooleanField(default=True, help_text='Enable SEO optimizations for this category'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Canonical URL (optional)', null=True),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='jsonld_override',
            field=models.TextField(blank=True, help_text='Custom JSON-LD data (optional JSON override)'),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='jsonld_type',
            field=models.CharField(blank=True, help_text="JSON-LD schema type (e.g., 'WebPage', 'Article')", max_length=100),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description (optional, falls back to meta_description)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (optional, falls back to meta_title)', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='seo_enabled',
            field=models.BooleanField(default=True, help_text='Enable SEO optimizations for this page'),
        ),
    ]
