# Generated by Django 5.1.14 on 2025-11-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_blogpost_canonical_url_blogpost_jsonld_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='category',
            field=models.CharField(choices=[('museum', 'Museum'), ('viewpoint', 'Viewpoint'), ('neighborhood', 'Neighborhood'), ('landmark', 'Landmark'), ('park', 'Park'), ('beach', 'Beach'), ('shopping', 'Shopping'), ('restaurant', 'Restaurant'), ('nightlife', 'Nightlife'), ('cultural', 'Cultural Site'), ('historical', 'Historical Site'), ('other', 'Other')], default='other', help_text='Type of destination', max_length=20),
        ),
        migrations.AddField(
            model_name='destinationtranslation',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for listing pages', max_length=200),
        ),
    ]
